Feature/new design anna
CAFECA-IO/iSUN-ONE pull request #60
Opened 2024-06-18 10:26 UTC by jing12345678910

### DEVELOP
- RWD (mobile version) - solution page, OTC page, FAQ page, terms page, privacy page

### CHECK LIST
- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 0
- new Class / Component: 0
- new loop: 0
- new recursive: 0
- high risk: 0
- new sql: 0

### UML
- [Component Diagram](https://lucid.app/lucidchart/23862c50-adca-44ce-af40-b20a0a06180c/edit?page=0_0#)

2024-06-19 14:45 UTC, Luphia requested changes

2024-06-19 14:45 UTC, Luphia commented on src/styles/solution/solution_cards.module.css
- require indentation

2024-06-20 01:49 UTC, jing12345678910 commented on src/styles/solution/solution_cards.module.css
Indentation has been adjusted.

2024-06-20 02:00 UTC, Luphia approved these changes
- no bug found

2024-06-20 02:00 UTC, merged